"""The hooks refuse a commit message that credits an AI assistant.

The author of a commit in this project is the person who makes it: no
assistant as co-author, no session link, no "Generated with". That was a
rule kept by review alone, and review is exactly what a commit made in a
hurry skips. `commit-msg` refuses such a line in the message being written,
and `pre-push` in the messages of the commits a push would send, which also
covers a cherry-pick or a rebase that runs no commit hook.

Naming an assistant is fine otherwise: griot supports Claude Code, and a
commit says so. What is refused is a line that credits one.

Run for real, in throwaway repositories, as tests/test_git_hooks.py does.
"""

import subprocess
import sys

import pytest
from hook_support import HOOKS, git as _git, make_repo, write_script

pytestmark = pytest.mark.skipif(sys.platform == "win32", reason="the hooks are bash scripts")

CREDITS = [
    "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>",
    "co-authored-by: GitHub Copilot <copilot@github.com>",
    "Co-authored-by: ChatGPT <noreply@openai.com>",
    "Claude-Session: https://claude.ai/code/session_0123456789",
    "Claude-Session: 0123456789abcdef",
    "https://claude.ai/code/session_0123456789",
    "\U0001F916 Generated with [Claude Code](https://claude.com/claude-code)",
    "Generated by Gemini",
    "Generated with \U0001F916 [Claude Code](https://claude.com/claude-code)",
    "Co-authored-by: Cursor Agent <cursoragent@cursor.com>",
    "Co-authored-by: Devin AI <158243242+devin-ai-integration[bot]@users.noreply.github.com>",
    "Co-authored-by: Aider (gpt-4o) <noreply@aider.chat>",
    "Co-authored-by: Windsurf <windsurf@codeium.com>",
    "Co-authored-by: Windsurf Cascade <cascade@example.com>",
    "Co-authored-by: Claude Sonnet 4 <claude@example.com>",
    # A bullet or prose is not a quote: only what follows a `>` or a `<` on
    # its line is someone else's text.
    "- Generated with Copilot by upstream",
    "docs: the notes (generated with Claude Code)",
    "See https://claude.ai/code/session_0123456789",
]

FINE = [
    "Co-Authored-By: Maria Silva <maria@example.com>",
    "feat: the installer registers griot for Claude Code",
    "docs: how to use griot from Copilot, Gemini or Claude Code",
    "fix: generated with the template, as before",
    "docs: generated with a script, then checked against Claude Code and Gemini",
    # People: a given name or an employer is not an assistant.
    "Co-authored-by: Claude Dupont <claude@example.fr>",
    "Co-authored-by: Ana Lima <ana@openai.com>",
    "Co-authored-by: Devin Smith <devin@example.com>",
    # Someone else's words, quoted: a release note Dependabot quotes, as a
    # Markdown quote or inside the HTML it writes (<blockquote><li>...).
    "> Generated with Copilot by upstream",
    "> \U0001F916 Generated with [Claude Code](https://claude.com/claude-code)",
    "  > > https://claude.ai/code/session_0123456789",
    "<li>Generated with Copilot by upstream</li>",
    '<p><a href="https://claude.ai/code/session_0123456789">the session</a></p>',
    # Inside a tag, before any `>`: a wrapped line of that HTML can start so.
    '<a href="https://claude.ai/code/session_0123456789">the session</a>',
    '<img alt="Generated with Claude Code" src="badge.svg">',
]


@pytest.fixture
def repo(tmp_path):
    """No sensitive-terms.txt on purpose: the rule does not depend on it."""
    return make_repo(tmp_path / "repo", write_script(tmp_path / "gitleaks-stub", "exit 0\n"))


@pytest.fixture
def remote(repo, tmp_path):
    path = tmp_path / "remote.git"
    assert _git(tmp_path, "init", "-q", "--bare", "-b", "main", str(path), env=repo.env).returncode == 0
    assert _git(repo, "remote", "add", "origin", str(path), env=repo.env).returncode == 0
    _commit(repo, "first")
    return path


def _commit(repo, message, hooks=True, name="notes.md"):
    (repo / name).write_text(message + "\n")
    assert _git(repo, "add", name, env=repo.env).returncode == 0
    return _git(repo, "commit", "-q", "-m", message, *([] if hooks else ["--no-verify"]), env=repo.env)


def _count(repo):
    done = _git(repo, "rev-list", "--count", "HEAD", env=repo.env)
    return int(done.stdout.strip()) if done.returncode == 0 else 0


# --- commit-msg -------------------------------------------------------------------------------------


@pytest.mark.parametrize("line", CREDITS)
def test_a_message_that_credits_an_assistant_is_refused(repo, line):
    done = _commit(repo, f"fix: something\n\n{line}")

    assert done.returncode != 0 and "attribution" in done.stderr
    assert _count(repo) == 0


@pytest.mark.parametrize("line", FINE)
def test_a_message_that_only_names_one_or_credits_a_person_goes_through(repo, line):
    done = _commit(repo, f"{line}\n\nbody")

    assert done.returncode == 0, done.stderr


def test_a_template_comment_in_an_editor_is_not_read(repo, tmp_path):
    """git takes its own comment lines out of a message written in an
    editor: a credit there never reaches the commit."""
    message = tmp_path / "MSG"
    message.write_text(f"docs: fine\n# {CREDITS[0]}\n")

    done = subprocess.run([str(HOOKS / "commit-msg"), str(message)], capture_output=True, text=True, cwd=repo,
                          env={**repo.env, "GIT_EDITOR": "vi"})

    assert done.returncode == 0, done.stderr


def test_a_credit_on_a_comment_line_given_with_m_is_refused(repo):
    """With -m there is no template, and git keeps a line that starts with #."""
    done = _commit(repo, f"fix: something\n\n# {CREDITS[0]}")

    assert done.returncode != 0 and "attribution" in done.stderr


# --- pre-push ---------------------------------------------------------------------------------------


def test_a_commit_that_credits_an_assistant_is_not_pushed(repo, remote):
    assert _commit(repo, f"fix: something\n\n{CREDITS[0]}", hooks=False).returncode == 0
    head = _git(repo, "rev-parse", "--short", "HEAD", env=repo.env).stdout.strip()

    done = _git(repo, "push", "-q", "origin", "main", env=repo.env)

    assert done.returncode != 0 and "attribution" in done.stderr and head in done.stderr
    assert _git(repo, "--git-dir", str(remote), "rev-parse", "-q", "--verify", "main", env=repo.env).returncode != 0


def test_a_push_of_clean_commits_goes_through(repo, remote):
    assert _commit(repo, FINE[1], name="more.md").returncode == 0

    done = _git(repo, "push", "-q", "origin", "main", env=repo.env)

    assert done.returncode == 0, done.stderr


QUOTING_A_CREDIT = """build(deps): bump setup-uv from 10.2.0 to 10.3.0

<blockquote>
<li>Generated with Copilot by upstream</li>
</blockquote>
> https://claude.ai/code/session_0123456789"""


def test_a_commit_that_quotes_a_credit_is_pushed(repo, remote):
    """pre-push reads messages through git's own regex: a quote has to pass
    there too, not only in grep."""
    assert _commit(repo, QUOTING_A_CREDIT, hooks=False, name="more.md").returncode == 0

    done = _git(repo, "push", "-q", "origin", "main", env=repo.env)

    assert done.returncode == 0, done.stderr


@pytest.mark.parametrize("hooks", [True, False], ids=["commit-msg", "pre-push"])
def test_a_quote_on_one_line_does_not_cover_a_credit_on_the_next(repo, remote, hooks):
    """`<` or `>` exempts what follows it on its own line only: a quote
    earlier in the message does not stretch over a credit below it."""
    message = f"fix: the <details> block\n\n> quoted\n{CREDITS[6]}"
    if hooks:
        done = _commit(repo, message, name="more.md")
    else:
        assert _commit(repo, message, hooks=False, name="more.md").returncode == 0
        done = _git(repo, "push", "-q", "origin", "main", env=repo.env)

    assert done.returncode != 0 and "attribution" in done.stderr


def test_the_rule_holds_with_a_terms_list_too(repo):
    (repo / ".git" / "sensitive-terms.txt").write_text("acme-private\n")

    done = _commit(repo, f"fix: something\n\n{CREDITS[0]}")

    assert done.returncode != 0 and "attribution" in done.stderr


def test_an_annotated_tag_that_credits_an_assistant_is_not_pushed(repo, remote):
    assert _git(repo, "tag", "-a", "v1", "-m", f"release\n\n{CREDITS[0]}", env=repo.env).returncode == 0

    done = _git(repo, "push", "-q", "origin", "main", "v1", env=repo.env)

    assert done.returncode != 0 and "attribution" in done.stderr and "v1" in done.stderr
